org.gradle.caching=true
org.gradle.parallel=true
org.gradle.vfs.watch=true
org.gradle.incremental=true
org.gradle.configureondemand=true
org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn
org.gradle.logging.level=lifecycle
org.gradle.warning.mode=all
org.gradle.console=verbose
